### ISSUE TITLE
Using chrome canary, CDP.Close has no effect

### ISSUE THREAD

**Issue by vvo** [cyrus-and/chrome-remote-interface#107] opened 2017-04-19 14:21 UTC
I am using chrome canary 60.0.3074.0 on OSX (launching via /Applications..)

![image](https://cloud.githubusercontent.com/assets/123822/25184838/dcea44fc-251b-11e7-8548-0c903392d887.png)

Using CDP.close({id: target.id}) is not throwing but it's also not closing the target (tab in my case).

Using https://store.docker.com/community/images/yukinying/chrome-headless-browser seems to be ok

How can I debug this since there's no error message. I believe this is not a bug from your library but at the same time I tried to search for bugs at https://bugs.chromium.org/p/chromium/issues/list?can=2&q=Proj%3DHeadless and found nothing.

Is there another repo I should look for?

**Comment by cyrus-and** [comment] 2017-04-19 17:32
> Using https://store.docker.com/community/images/yukinying/chrome-headless-browser seems to be ok

That's because it's using Chrome version 59. It's probably a regression, it was broken in 57 and then fixed in 59. Try interacting with the HTTP endpoint directly:

```
curl -vg http://localhost:9222/json/list
curl -vg http://localhost:9222/json/new
curl -vg http://localhost:9222/json/close/<id>
```

If that's the case it's probably worth to open a new issue at the Chromium project. Feel free to link it here then.

**Comment by vvo** [comment] 2017-04-19 17:58
Done, https://bugs.chromium.org/p/chromium/issues/detail?id=713268&can=2&start=0&num=100&q=Proj%3DHeadless&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

BTW where is the spec for http://localhost:9222/json/ endpoint?

**Comment by cyrus-and** [comment] 2017-04-19 18:03
> Done

Great thanks!

> BTW where is the spec for http://localhost:9222/json/ endpoint?

[devtools_http_handler.cc] ^_^

[devtools_http_handler.cc]: https://chromium.googlesource.com/chromium/src/+/master/content/browser/devtools/devtools_http_handler.cc

**Comment by cyrus-and** [comment] 2017-04-28 21:30
Fixed now: https://bugs.chromium.org/p/chromium/issues/detail?id=713268

**Closed by cyrus-and** 2017-04-28 21:30 UTC
Labels: external issue
