### ISSUE TITLE
Something similar for firefox?

### ISSUE THREAD

**Issue by klodoma** [cyrus-and/chrome-remote-interface#68] opened 2016-12-06 10:10 UTC
Hi, 

First, this is NOT an issue, but I need to ask you  :) as it seems you have experience in the field.
I am using an older version of this software and it's cool. 

I was wondering if you are aware of something similar for Firefox. Mainly what I am looking for:
- connect to firefox with nodejs
- open url
- listen to the console

Thanks!

**Comment by cyrus-and** [comment] 2016-12-06 10:56
Hi, you can use this module with every application that implement the Chrome Debugging Protocol, you can find a [table][1] in the README. As you can see, Firefox is not listed (yet?) albeit it provides a [Remote Debugging Protocol][2] itself, since to my knowledge it does not exposes a compatible interface, i.e., you would need an adapter in the middle, in particular I was aware of [remotedebug-firefox-adapter][3] which seems to be deprecated now.

But of course I might be wrong.
@jasonLaster, @auchenberg can you shed some light on this?

[1]: https://github.com/cyrus-and/chrome-remote-interface#implementations
[2]: https://wiki.mozilla.org/Remote_Debugging_Protocol
[3]: https://github.com/RemoteDebug/remotedebug-firefox-adapter

**Comment by jasonLaster** [comment] 2016-12-06 17:11
Hi @klodoma, if you can be patient for a couple of days, i'll be bumping [devtools-client-adapter](https://github.com/devtools-html/debugger.html/tree/master/packages/devtools-client-adapters), which is the connection layer we use on the [Debugger](https://github.com/devtools-html/debugger.html). Client adapter connects to either firefox or chrome and will use CRI soon w/ chrome. You can see [here](https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-client-adapters/src/firefox.js#L54-L61) that it does plenty to help you with firefox's internal client.

With that said, It would be nice to have an adapter system so that CRI could claim to have support for firefox e.g.

```js
const CDP = require('chrome-remote-interface');
require('chrome-remote-interface-firefox-adapter');

CDP.List({ port: 6080 }).then(tabs => console.log(tabs)
```

In theory, it would be pretty easy to conform to the HTTP api and perhaps the *only* challenge is to not try to build a protocol message and let the adapter do that.

@cyrus-and, @auchenberg what do you think? If we build a Firefox adapter, would you share your adapters :)

**Comment by klodoma** [comment] 2016-12-06 17:54
Hi @jasonLaster, 

Sure I'm in no rush for the moment. I was wondering if there is a similar possibility to work with Firefox, as I am using this for chrome for a "backend video recording" and I have some problems with Chrome (it just crashes in some cases), so I was thinking to try Firefox as alternative.

So, whatever you do, please keep me updated. 

Thanks a lot!

**Comment by cyrus-and** [comment] 2016-12-06 18:11
@jasonLaster IMHO would be better that third-party implementations which want to support the Chrome Debugging Protocol provide their own adapter (e.g., [edge-diagnostics-adapter]) if they cannot/don't want to support it directly (e.g., Node.js). I think it's in their own interest to do that.

Besides, wasn't this the original purpose of @RemoteDebug?

[edge-diagnostics-adapter]: https://github.com/Microsoft/edge-diagnostics-adapter

**Comment by jasonLaster** [comment] 2016-12-06 18:23
Couple of comments:
1. lets assume adapters target CDP 1.2 or latest stable
2. the goal is to make it easy to use any adapter. Currently it's likely each would have a different API and other inconsistencies
 * for instance my client adapter has the method `connectClient` instead of List because of firefox semantics.
* [edge](https://github.com/Microsoft/edge-diagnostics-adapter/blob/master/src/adapterService/edgeAdapterService.ts#L53-L65) has a separate process, type script ...
3. I don't want to add complexity that you have to maintain

**Comment by auchenberg** [comment] 2016-12-08 03:40
The intent of @RemoteDebug is to have a specification in place that each browser vendor can implement within their runtimes, and libraries like `chrome-remote-interface` can adhere to.

Going forward it's safe to assume runtimes will expose CDP 1.2 or similar, and I would expect Firefox to either support CDP/RemoteDebug natively or supply an adapter which `chrome-remote-interface` can connect to transparently. https://github.com/Microsoft/edge-diagnostics-adapter is an example of this for Edge.

if an adapter is implemented correctly there wouldn't be any difference for `chrome-remote-interface` whether it connects to  Chrome, Edge or Firefox.

**Comment by cyrus-and** [comment] 2017-04-15 17:54
I'm closing this since there's nothing I can do about it. But feel free to comment if there is any news.

**Comment by jasonLaster** [comment] 2017-04-15 17:55
Thanks. I understand

**Closed by cyrus-and** 2017-04-15 17:54 UTC
Labels: question

**Comment by paulirish** [comment] 2018-12-07 05:17
Fwiw pptr-firefox has custom Firefox binaries with custom patches.

**Comment by cyrus-and** [comment] 2018-12-07 11:38
@paambaati if Firefox supports the same protocol and HTTP methods then it's already supported, it's just a matter of updating the README.

**Comment by martinpitt** [comment] 2019-10-07 20:05
Firefox [claims](https://firefox-source-docs.mozilla.org/remote/index.html) to have native CDP support now; after

    firefox --remote-debugger --no-remote

one can actually connect to it using `node_modules/.bin/chrome-remote-interface inspect`, but every command fails like this:
```
>>> (node:139493) UnhandledPromiseRejectionWarning: Error: TypeError: this.mm is null:
	executeInChild@chrome://remote/content/sessions/TabSession.jsm:82:5
	onMessage@chrome://remote/content/sessions/TabSession.jsm:74:14
	onPacket@chrome://remote/content/Connection.jsm:93:29
	onMessage@chrome://remote/content/server/WebSocketTransport.jsm:85:18
	handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:67:14
    at /var/home/martin/upstream/cockpit/node_modules/chrome-remote-interface/lib/chrome.js:93:35
    at Chrome._handleMessage (/var/home/martin/upstream/cockpit/node_modules/chrome-remote-interface/lib/chrome.js:256:17)
    at WebSocket.<anonymous> (/var/home/martin/upstream/cockpit/node_modules/chrome-remote-interface/lib/chrome.js:234:22)
    at WebSocket.emit (events.js:209:13)
    at WebSocket.EventEmitter.emit (domain.js:476:20)
    at Receiver.receiverOnMessage (/var/home/martin/upstream/cockpit/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:209:13)
    at Receiver.EventEmitter.emit (domain.js:476:20)
    at Receiver.dataMessage (/var/home/martin/upstream/cockpit/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/var/home/martin/upstream/cockpit/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:352:17)
(node:139493) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:139493) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I. e. whatever `this.mm` is, it seems Chromium's and Firefox' TabSession implementation in the protocol is somehow different.

**Comment by cyrus-and** [comment] 2019-10-07 20:25
@martinpitt well it seems to work here (Firefox 68):

```
$ chrome-remote-interface list
[
    {
        "id": 3,
        "type": "page",
        "url": "about:home",
        "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/3"
    }
]
$ chrome-remote-interface inspect
>>> Page.navigate({url:'http://example.com'})
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [],
     [Symbol(kWeak)]: WeakReference {} } }
>>> (node:9315) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
$ chrome-remote-interface list
[
    {
        "id": 3,
        "type": "page",
        "url": "http://example.com/",
        "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/3"
    }
]
```

**Comment by philippotto** [comment] 2020-04-26 08:36
I get `Error: Parse Error: Expected HTTP/` when executing `chrome-remote-interface -p  6000 list`. Any idea on how to debug this further?

**Comment by cyrus-and** [comment] 2020-04-26 09:19
@philippotto what version of Firefox are you using, and how did  you run it? Plus what's the output of the following?

```
curl http://127.0.0.1:6000/json/list
```

**Comment by philippotto** [comment] 2020-04-28 08:01
> @philippotto what version of Firefox are you using, and how did you run it? Plus what's the output of the following?
> 
> ```
> curl http://127.0.0.1:6000/json/list
> ```

Thanks for your prompt reply! This command yields `curl: (52) Empty reply from server`.

I'm on Ubuntu 18.04 with Firefox 75.0 (64-bit). I started firefox with `firefox --start-debugger-server`.
I enabled "Remote Debugging" in the devtool settings and I also set "devtools.debugger.prompt-connection" in `about:config` to false since I would get a confirmation prompt [1] in firefox everytime I executed chrome-remote-interface. I assumed that the prompt would somehow interfere with the connection establishment. But it does not seem to make a difference (regardless of the setting, the `curl` command exists immediately).


[1]:
```
An incoming request to permit remote debugging connection was detected. A remote client can take complete control over your browser!
```

**Comment by cyrus-and** [comment] 2020-04-28 08:09
@philippotto I used port 6000 because of you example. Try this:

```console
$ firefox --remote-debugger
$ chrome-remote-interface list
```

**Comment by philippotto** [comment] 2020-04-28 08:23
`firefox --remote-debugger`

Does this default to port 6000? `curl`ing to localhost:6000/json/list now yields `Connection refused`.
Calling `chrome-remote-interface list` without port parameter only lists my Chrome targets.

**Comment by cyrus-and** [comment] 2020-04-28 08:31
> Does this default to port 6000?

Defaults to port 9222. If you want to change it try this:

```console
$ firefox --remote-debugger localhost:6000
$ chrome-remote-interface -p 6000 list
```

Note that you need to specify `localhost` apparently.

**Comment by philippotto** [comment] 2020-04-28 09:54
> Defaults to port 9222.

Are you sure? This page https://developer.mozilla.org/de/docs/Tools/Remote_Debugging/Debugging_Firefox_Desktop says that the default port is 6000. Or is this a different concept?
Do you happen to know where I can find some official documentation about this firefox feature? I can only find the before-mentioned page which is a draft. The CLI arguments don't show up in `man firefox` or `firefox --help` either.

> ```
> $ firefox --remote-debugger localhost:6000
> $ chrome-remote-interface -p 6000 list
> ```
> 
> Note that you need to specify localhost apparently.


Unfortunately, this doesn't work for me either. I get `Error: connect ECONNREFUSED 127.0.0.1:6000
`.  If I start firefox with `firefox --start-debugger-server` instead, I at least get `curl: (52) Empty reply from server`.

**Comment by cyrus-and** [comment] 2020-04-28 16:48
@philippotto my bad, I was using an old (70) version of Firefox, with the latest I reproduce what you're experiencing. This looks like a bug in Firefox or lack of documentation on their end. I suggest to file an issue or ask specific help to their development team. Feel free to link back here and/or post updates here. Thank you!
