### ISSUE TITLE
README does not work with TypeScript (e.g. "requestWillBeSent" does not exist)

### ISSUE THREAD

**Issue by slhck** [cyrus-and/chrome-remote-interface#500] opened 2022-08-22 11:12 UTC
## Environment

| Component | Version
|-|-
| Node.js						| v16.16
| Client (Chrome/Chromium/...)	| Chrome 104
| OS running Node.js			| macOS
| OS running the client			| macOS
| chrome-remote-interface		| 0.31.3

Is the client running in a container? No

## Description

The shorthand methods for events are not available.

Also, calling `.enable()` without parameters causes type errors.

## Example

Directly taken from the README:

```js
import CDP from "chrome-remote-interface";

async function setup() {
  // connect to endpoint
  const client = await CDP();
  // extract domains
  const { Network } = client;
  // setup handlers
  Network.requestWillBeSent((params) => {
    console.log(params.request.url);
  });
  // enable events then start!
  await Network.enable();
}
```

This shows the following TypeScript errors for `requestWillBeSent`:

> Property 'requestWillBeSent' does not exist on type 'NetworkApi'.

And for `enable()`:

> Expected 1 arguments, but got 0.

Indeed there is no such function `requestWillBeSent` in `node_modules/@types/chrome-remote-interface/node_modules/devtools-protocol/types/protocol-proxy-api.d.ts` – which is what TypeScript is using to look up the definitions from the original API. But seeing that this is a method that this project uses as a shorthand, I am not expecting this to be part of the official API either …

(Should this be an issue in the `@types/chrome-remote-interface` package?)

**Comment by cyrus-and** [comment] 2022-08-24 19:29
> Should this be an issue in the `@types/chrome-remote-interface` package?

Yes, I don't offer any support for the typings, I'm sorry. You should ping the typings authors.

/cc @westy92 @kazarmy 

Note though, `requestWillBeSent` is not really a protocol function (method), it's an event, which when is called in that way it simply registers a callback.

Closing, but feel free to add further information here.

**Closed by cyrus-and** 2022-08-24 19:29 UTC

**Comment by westy92** [comment] 2022-08-24 19:36
You can find an example of this in the typings tests: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome-remote-interface/chrome-remote-interface-tests.ts

Instead, try:

```ts
client['Network.requestWillBeSent']((params) => {
  console.log(params.request.url);
});

await Network.enable({});
```

**Comment by slhck** [comment] 2022-08-24 19:45
> You can find an example of this in the typings tests: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome-remote-interface/chrome-remote-interface-tests.ts
> 
> Instead, try:
> 
> ```ts
> client['Network.requestWillBeSent']((params) => {
>   console.log(params.request.url);
> });
> 
> await Network.enable({});
> ```

@westy92 The README from this package however shows that I can use `Network.requestWillBeSent`. So shouldn't the type definitions support this?

> Note though, requestWillBeSent is not really a protocol function (method), it's an event, which when is called in that way it simply registers a callback.

Right, as mentioned in the original issue, I am aware that this is just a non-official shorthand you added for registering a callback on this event.

**Comment by kazarmy** [comment] 2022-08-25 14:30
> So shouldn't the type definitions support this?

It should but the type definitions are generated from source material and it doesn't appear possible currently to generate the event typings automatically using the TypeScript type system.

A general-purpose language can do that though and I have some (old) typings at https://github.com/kazarmy/devtools-protocol/tree/master/types that do have event typings including for `Network.requestWillBeSent`. They can be integrated into local typings -- https://github.com/cyrus-and/chrome-remote-interface/issues/112#issuecomment-895292654 has details (I do not know how and why the `import` statements work but they still do with the latest VSCode). Sorry no "wizard" is planned; I don't have the resources to support one.

**Comment by slhck** [comment] 2022-08-26 08:29
I see, and I understand that it would be a considerable effort to implement these shorthands automatically/procedurally.

That said, this leaves this package in a bit of an undesirable state, where even the basic README throws errors when used in a TypeScript project. Perhaps it would be helpful to make a note of this somewhere in the documentation to avoid having users like me ask about it?

**Comment by cyrus-and** [comment] 2022-08-26 08:46
Feel free to open a PR to add some note [here](https://github.com/cyrus-and/chrome-remote-interface#typescript-support).

**Comment by kazarmy** [comment] 2022-08-30 11:07
> I see, and I understand that it would be a considerable effort to implement these shorthands automatically/procedurally.

Possibly currently the best way to obtain these shorthands is to run `patch-package` on the `devtools-protocol` dependency, after replacing the types inside with the ones from https://github.com/kazarmy/devtools-protocol/tree/master/types for instance. The patch might probably be permanent, but it can be under version control and if it can be proven that the patch works, well ...

**Comment by kazarmy** [comment] 2022-09-15 15:35
> Possibly currently the best way to obtain these shorthands ...

Apologies for totally misreading this issue (probably because I skimmed it way too fast). Now I realize that the problem is not with a statement like `await Page.loadEventFired()` but with statements like:

1. `Network.requestWillBeSent(<callback>)` ... the typings don't have the shorthand callback version for events.
2. `Network.enable(<object_param>)` ... the typing generator is not aware that all the properties of the object parameter are optional.

**Comment by slhck** [comment] 2022-09-15 15:36
Yes, that is exactly the issue 😊

**Comment by kazarmy** [comment] 2022-12-16 17:07
> See [kazarmy/devtools-protocol@cd0804e/types](https://github.com/kazarmy/devtools-protocol/tree/cd0804e422523415f92722d2b4c5cdd8d30c6a3d/types) for devtools-protocol@0.0.927104 typings that cover the above.

As of @types/chrome-remote-interface 0.31.8, the custom typings above are no longer needed.

**Comment by slhck** [comment] 2023-01-05 13:46
Great, just tried it. Thanks! 🎉
