### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by mato75** [cyrus-and/chrome-remote-interface#35] opened 2016-06-14 08:14 UTC
Unfortunattly I don't know how this error was produced, only that it was logged in exceptions and I thought you may want to know about it.

````
/chrome-remote-interface/lib/devtools.js:23:25","  
 at /chrome-remote-interface/lib/devtools.js:94:13","  
 at IncomingMessage.<anonymous> (/chrome-remote-interface/lib/devtools.js:142:17)"," 
 at emitNone (events.js:85:20)","   
 at IncomingMessage.emit (events.js:179:7)","    
 at endReadableNT (_stream_readable.js:913:12)","   
 at _combinedTickCallback (internal/process/next_tick.js:74:11)","   
 at process._tickCallback (internal/process/next_tick.js:98:9)"],"level":"error","message":"uncaughtException: Cannot read property 'startsWith' of undefined","timestamp":"2016-06-14T04:45:55.134Z"}
````

**Comment by cyrus-and** [comment] 2016-06-14 13:38
Thanks for reporting, can you tell me what Chrome (or NW.js) version and OS are you using?

**Comment by mato75** [comment] 2016-06-15 11:54
Linux: 4.2.0-36-generic #42~14.04.1-Ubuntu SMP Fri May 13 17:27:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
NW - 0.14.5
Chromium 50.0.2661.102 Ubuntu 14.04

**Comment by cyrus-and** [comment] 2016-08-30 16:14
So it turned out that the cause was pretty silly: `startsWith` was not defined in older versions of Node.js, so if you were using an old version back then, we can say it's fixed now, otherwise it's still a mystery. Closing it though, let me know if it will happen again.

I didn't think about it at first because some other user reported a similar issue but that was an intermittent behavior.

**Closed** 2016-08-30 16:14 UTC
Labels: bug, irreproducible
