### ISSUE TITLE
can not connect to chrome behind ssl nginx after updating to latest

### ISSUE THREAD

**Issue by hbakhtiyor** [cyrus-and/chrome-remote-interface#311] opened 2017-12-17 07:24 UTC
| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 16.04
| Node.js					| v8.9.3
| Chrome/Chromium/...		| 65.0.3294.5 dev
| chrome-remote-interface	| v0.25.4

Is Chrome running in a container? YES

example:

```js
const CDP = require('chrome-remote-interface');

async function navigateInANewTab(url) {
    const options = { host: 'host', port: 443, secure: true };
    const tab = await CDP.New(options);
    const client = await CDP(Object.assign(options, {tab})); // the error happened here 
}

navigateInANewTab('https://github.com');
```
and `await CDP.New(options);` returning with `ws` prefix, not `wss`, see at `devtoolsFrontendUrl` and `webSocketDebuggerUrl`

```
   { description: '',
     devtoolsFrontendUrl: '/devtools/inspector.html?ws=host/devtools/page/(8E69E9E19E9EE765CFD0BD18CDDCAFB)',
     id: '(8E69E9E19E9EE765CFD0BD18CDDCAFB)',
     title: '',
     type: 'page',
     url: 'about:blank',
     webSocketDebuggerUrl: 'ws://host/devtools/page/(8E69E9E19E9EE765CFD0BD18CDDCAFB)' } }

```

the error:
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:329:15)
    at TLSSocket.socketCloseListener (_http_client.js:361:23)
    at emitOne (events.js:120:20)
    at TLSSocket.emit (events.js:210:7)
    at _handle.close (net.js:547:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7) code: 'ECONNRESET' }
```

i tried with `wscat` and localhost (not ssl) and works well, i think your new release ignoring `secure` option

**Comment by hbakhtiyor** [comment] 2017-12-17 09:02
@cyrus-and why the default option of `local` [the param](https://github.com/cyrus-and/chrome-remote-interface#cdpoptions-callback) is false? is it check protocol for every request when the local option is false?

**Comment by cyrus-and** [comment] 2017-12-17 22:00
> i tried with wscat and localhost (not ssl) and works well

AFAIK it should work with the SSL version too using `wscat`, instead in my tests I get `error: Error: socket hang up`, so I don't see how #312 can fix this. (I'd like to reproduce and fix it on my side before.)

I'm briefly testing this with [node-http-proxy](https://github.com/nodejitsu/node-http-proxy):

```js
const fs = require('fs');
const httpProxy = require('http-proxy');

httpProxy.createServer({
    ws: true,
    target: {
        host: 'localhost',
        port: 9222
    },
    ssl: {
        key: fs.readFileSync('/path/to/key.pem', 'utf8'),
        cert: fs.readFileSync('/path/to/cert.pem', 'utf8')
    }
}).listen(10000);
```

---

> why the default option of local the param is false?

Because the local version is not reliable.

> is it check protocol for every request when the local option is false?

Not for every request, upon connection only.

**Comment by hbakhtiyor** [comment] 2017-12-18 02:38
> AFAIK it should work with the SSL version too using wscat

yeah, but i mean non-ssl for only localhost

> so I don't see how #312 can fix this.

because, it's overwrite the passed port to null (since it uses standard port which returns null)

**Comment by cyrus-and** [comment] 2017-12-18 12:22
Alright, yes, I was trying with a different port. 80 and 443 are omitted by Chrome (not a great choice IMHO).

Merged #312 (reworded).

Thanks!

**Closed** 2017-12-18 12:22 UTC

**Comment by hbakhtiyor** [comment] 2017-12-19 02:38
still sometime getting `Error: socket hang up` error, not like before continually 
i can't exactly reproduce it.

**Comment by cyrus-and** [comment] 2017-12-19 10:50
OK, feel free to provide additional info if you find out why/when it happens.
