### ISSUE TITLE
Captured image within Headless Chrome wraps page's content until height requirement is met

### ISSUE THREAD

**Issue by cratter49** [cyrus-and/chrome-remote-interface#310] opened 2017-12-14 01:33 UTC
| Component | Version
|-|-
| Operating system	  	 	| Chrome is running within a Docker container on a image that is based on Ubuntu 14.04
| Node.js					| 8.8.1
| Chrome/Chromium/...		| Google Chrome 64.0.3282.24 dev
| chrome-remote-interface	| 0.24.4

Is Chrome running in a container? YES 

@cyrus-and I'm currently experiencing a very odd issue possibly regarding the functionality of `Page.captureScreenshot` or `Emulation.setDeviceMetricsOverride`.

Here's some background on how the program works up to the problem I'm seeing:

 I'm starting a `Node.js` script which launches headless chrome from Python in order to generate a PDF containing images of C3/D3 charts within a Jupyter notebook. After headless chrome launches I wait for the page to load using `Page.loadEventFired` and then execute the rest of the code. Subsequently, the viewport resolution is dynamically set by using the calculated page height and passing that to `Emulation.setDeviceMetricsOverride`. After that occurs, I then call `Page.captureScreenshot`, write that to a file on disk, and end the program there. The resulting image contains the correct dimensions, including the calculated height. However, as you can see below, the image repeats the notebook's contents two times and does not contain the full content of the page representing the notebook. This is because when the image repeats itself, it had only captured about 50% of the content of the actual notebook.

![image 1](https://user-images.githubusercontent.com/5606728/33970938-afee7bc4-e02a-11e7-8163-665b1b1a52ec.png)

There seems to be some sort of wrapping of the page's content here. Any idea what could be going on?

**Comment by cyrus-and** [comment] 2017-12-14 12:45
I think that Chrome is experiencing problems with such a huge image. AFAIK there's nothing (CDP-side) that can cause such behavior.

Are you able to provide a minimal example to reproduce this?

I suggest to file an [upstream issue](crbug.com) or to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol), feel free to post the link here if you decide to do so.

**Comment by cratter49** [comment] 2017-12-14 17:49
@cyrus-and Smaller notebooks with less cells and charts cannot reproduce this error. We had this working with PhantomJS before without allocating extra memory to the headless browser. 

I'll post links of the threads I start in the other groups here.

**Comment by cyrus-and** [comment] 2017-12-14 18:50
Thanks, fixed!

I'm closing this since it's not a problem with CRI, feel free to add comments though.

**Closed by cyrus-and** 2017-12-14 18:50 UTC
