### ISSUE TITLE
Load event never fired

### ISSUE THREAD

**Issue by pedro93** [cyrus-and/chrome-remote-interface#176] opened 2017-06-26 10:14 UTC
I'm trying to use chrome-launcher and CRI for headless web scrapping but chrome-remote-interface does not seem to connect to the launched chrome instance via the designated port. Am I doing something wrong? If I'm asking this in the incorrect place I would appreciate being directed to the correct place.

```js
const chromeLauncher = require('chrome-launcher');
const chromeInterface = require('chrome-remote-interface');

async function run() {
    let chrome;
    try {
        chrome = await chromeLauncher.launch({
            startingUrl: "https://www.google.com",
            chromeFlags: ['--disable-gpu']
        });

        let client = await chromeInterface({ port: chrome.port });

        const { Page, Runtime, DOM } = client;
        await Page.enable();
        await Page.loadEventFired();
        await Runtime.enable();
        await DOM.enable();
        console.log("ready");

        let response = await Runtime.evaluate({ expression: 'document.title' });
        console.log("response is", response);

    } catch (e) {
        console.log(e);
    } finally {
        if (chrome) chrome.kill();
    }
}

run();
```

Thank you.

**Comment by pedro93** [comment] 2017-06-26 10:17
I've also tried to navigate to the the website explicly via CDP but to no avail

```js
const chromeLauncher = require('chrome-launcher');
const chromeInterface = require('chrome-remote-interface');

async function run() {
    let chrome;
    try {
        chrome = await chromeLauncher.launch({
            port: 9222,
            chromeFlags: ['--disable-gpu']
        });

        let client = await chromeInterface();

        const { Page, Runtime, DOM } = client;
        await Page.enable();
        await Runtime.enable();
        await DOM.enable();
        await Page.navigate({url: 'https://google.com'});
        await Page.loadEventFired();
        console.log("ready");

        let response = await Runtime.evaluate({ expression: 'document.title' });
        console.log("response is", response);

    } catch (e) {
        console.log(e);
    } finally {
        if (chrome) chrome.kill();
    }
}

run();
```

**Comment by cyrus-and** [comment] 2017-06-26 10:54
Possibly a duplicate of #174?

**Comment by cyrus-and** [comment] 2017-06-26 11:14
Also, the second version is the correct one because it avoids the possible race condition between the page load initiated by `startingUrl` and `Page.loadEventFired`.

**Comment by cyrus-and** [comment] 2017-06-26 12:06
> Possibly a duplicate of #174?

Not sure actually...

Anyway, I'm unable to reproduce your issue, what version of Chrome is chosen by `chrome-launcher'`?

**Comment by pedro93** [comment] 2017-06-26 14:19
Chrome version: 59.0.3071.109 (ubuntu 64 bit)

**Comment by cyrus-and** [comment] 2017-06-26 17:07
Same here but on Debian, still can't reproduce. Does that happen every time or intermittently?

**Comment by pedro93** [comment] 2017-06-26 17:41
Everytime, OS bug perhaps? I had 2 chrome instances, maybe that's why

**Comment by cyrus-and** [comment] 2017-06-26 18:06
> Everytime, OS bug perhaps?

Hm, highly unlikely.

> I had 2 chrome instances, maybe that's why

I don't think so but try with one, just in case.

**Comment by cyrus-and** [comment] 2017-06-29 09:17
> I don't think so but try with one, just in case.

Did you try that? Also, please explain the 2 instances scenario.

**Comment by pedro93** [comment] 2017-06-29 10:53
I already had a chrome window opened with several tabs from browsing. The code snippet would open a new window. 

I thought that maybe the first window was using the debugging port 9222 and be the reason CRI does not work. 
With no previous window opened the code example will still not work. I have to explicitly open chrome with:

```
$ google-chrome --remote-debugging-port=9222
```

Perhaps this is an issue with the chrome-launcher module.

**Comment by cyrus-and** [comment] 2017-06-29 11:05
> The code snippet would open a new window.

You can use chrome-launcher as you do in the first snippet to spawn a fresh new instance on a random port, in this case there should be surely no conflicts.

> I have to explicitly open chrome with:

And in this case does it work?

---

Just to be clear, the following should always work regardless of existing sessions:


```js
const chromeLauncher = require('chrome-launcher');
const chromeInterface = require('chrome-remote-interface');

async function run() {
    let chrome;
    try {
        chrome = await chromeLauncher.launch({
            chromeFlags: ['--disable-gpu', '--headless']
        });

        let client = await chromeInterface({port: chrome.port});

        const { Page, Runtime, DOM } = client;
        await Page.enable();
        await Runtime.enable();
        await DOM.enable();
        await Page.navigate({url: 'https://google.com'});
        await Page.loadEventFired();
        console.log("ready");

        let response = await Runtime.evaluate({ expression: 'document.title' });
        console.log("response is", response);
    } catch (e) {
        console.log(e);
    } finally {
        if (chrome) chrome.kill();
    }
}

run();
```

**Comment by pedro93** [comment] 2017-06-30 07:22
> And in this case does it work?
If I open chrome with the debugging port explicitly yes.

The snippet worked, took quite long though (21 seconds). Thank you for the help @cyrus-and !

**Comment by cyrus-and** [comment] 2017-06-30 08:13
The Chrome startup can be quite slow on some machine, but if you're just measuring the page load time then the cause may be the network. In any case it should not be related to this issue nor to headless mode, so I'm closing it for now. Feel free to add some other details if you discover something new.

You're, welcome!

**Closed by cyrus-and** 2017-06-30 08:13 UTC

**Comment by jeremygottfried** [comment] 2019-03-21 15:22
I tried this and it did not work unfortunately. Chrome-launcher loaded just fine, but the interface client did not. I waited at least 10 minutes for it to load.

> > The code snippet would open a new window.
> 
> You can use chrome-launcher as you do in the first snippet to spawn a fresh new instance on a random port, in this case there should be surely no conflicts.
> 
> > I have to explicitly open chrome with:
> 
> And in this case does it work?
> 
> Just to be clear, the following should always work regardless of existing sessions:
> 
> ```js
> const chromeLauncher = require('chrome-launcher');
> const chromeInterface = require('chrome-remote-interface');
> 
> async function run() {
>     let chrome;
>     try {
>         chrome = await chromeLauncher.launch({
>             chromeFlags: ['--disable-gpu', '--headless']
>         });
> 
>         let client = await chromeInterface({port: chrome.port});
> 
>         const { Page, Runtime, DOM } = client;
>         await Page.enable();
>         await Runtime.enable();
>         await DOM.enable();
>         await Page.navigate({url: 'https://google.com'});
>         await Page.loadEventFired();
>         console.log("ready");
> 
>         let response = await Runtime.evaluate({ expression: 'document.title' });
>         console.log("response is", response);
>     } catch (e) {
>         console.log(e);
>     } finally {
>         if (chrome) chrome.kill();
>     }
> }
> 
> run();
> ```

**Comment by cyrus-and** [comment] 2019-03-21 15:39
@jeremygottfried are you running Linux? If that's the case add the `--no-sandbox` flag.

**Comment by jeremygottfried** [comment] 2019-03-21 15:49
@cyrus-and I'm running macOS on a Macbook Pro

**Comment by cyrus-and** [comment] 2019-03-21 16:01
@jeremygottfried I don't know, I just tried with Chrome 73 on macOS and it worked as expected. Make sure you're using the latest versions of both his module and `chrome-launcher`.

**Comment by jeremygottfried** [comment] 2019-03-21 16:28
@cyrus-and I'm on Chrome 72 so I'll try 73 to see if that helps.
