### ISSUE TITLE
Network.getResponseBody fails for CORS requests sometimes?

### ISSUE THREAD

**Issue by wi-ski** [cyrus-and/chrome-remote-interface#148] opened 2017-06-01 21:16 UTC
Experiencing this issue very consistently where it will fail to retrieve a request body but ONLY for requests that are CORS requests.

And to confirm:

A. The requests is preceded by the typical OPTIONS request
B. The request fires
C. The request completes with a response

Subsequently calling `Network.getResponseBody` fails for the actual CORS requests.  I can successfully retrieve the request body for the OPTIONS request (which is empty)

Is this a known thing? The internets have no info on it.

**Comment by cyrus-and** [comment] 2017-06-03 11:31
So I tried to reproduce this issue with the following script, without luck:

```js
const CDP = require('chrome-remote-interface');
const http = require('http');

http.createServer((req, res) => {
    if (req.url === '/favicon.ico') {
        res.writeHead(404);
    } else {
        res.write(`<script>
const headers = new Headers();
headers.append('Content-Type', 'application/xml');
fetch('http://localhost:20000/post', {
    method: 'POST',
    headers
});
</script>`);
    }
    res.end();
}).listen(10000);

http.createServer((req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    if (req.method === 'POST') {
        res.write('data');
    }
    res.end();
}).listen(20000);

setTimeout(() => {
    CDP(async (client) => {
        const {Network, Page} = client;
        Network.requestWillBeSent(({requestId, request}) => {
            console.log(`REQ [${requestId}] ${request.method} ${request.url}`);
        });
        Network.responseReceived(async ({requestId, response}) => {
            const {body, base64Encoded} = await Network.getResponseBody({requestId});
            console.log(`RES [${requestId}] body: ${body}`);
            // console.log('{{{');
            // console.log(response);
            // console.log('}}}');
        });
        try {
            await Promise.all([Network.enable(), Page.enable()]);
            await Page.navigate({url: 'http://localhost:10000/index'});
            await Page.loadEventFired();
        } catch (err) {
            console.error(err);
        }
    }).on('error', (err) => {
        console.error(err);
    });
}, 1000);
```

Running it I get:

```
REQ [24773.28] GET http://localhost:10000/index
RES [24773.28] body: <script>
const headers = new Headers();
headers.append('Content-Type', 'application/xml');
fetch('http://localhost:20000/post', {
    method: 'POST',
    headers
});
</script>
REQ [24773.29] OPTIONS http://localhost:20000/post
REQ [24773.30] POST http://localhost:20000/post
RES [24773.29] body: 
RES [24773.29] body: 
RES [24773.30] body: data
```

As you can see the response body for the CORS request is successfully fetched (`data`), there's one weird thing though, there are two identical (check by uncommenting those above lines) responses for the `OPTIONS` request. But it's just a CDP thing as with Wireshark I correctly get:

```
GET /index HTTP/1.1
HTTP/1.1 200 OK
OPTIONS /post HTTP/1.1
HTTP/1.1 200 OK
POST /post HTTP/1.1
HTTP/1.1 200 OK
```

Not sure if this is the intended behavior or a bug with Chrome.

**Comment by wi-ski** [comment] 2017-06-05 22:01
A. Thank you for looking into this.  Much appreciated.  And thank you for the work you've done on this project.

B. That double-up phenomenon for the options request is interesting.  Ill spend some time and look into that possibly being the issue and post any info I get here as to help future google-ites.

**Comment by cyrus-and** [comment] 2017-06-05 23:14
You're welcome!

Feel free to quote this discussion if you decide to file an issue upstream ([here][1] or [here][2]).
Remember that there's also a [Google Group][3] for protocol-related questions.

[1]: https://github.com/ChromeDevTools/devtools-protocol/issues
[2]: https://bugs.chromium.org/p/chromium/issues/list
[3]: https://groups.google.com/forum/#!forum/chrome-debugging-protocol

**Comment by cyrus-and** [comment] 2017-06-12 16:15
I'm closing this as there's nothing I can do about it but please feel free to add any information if you find something new.

**Closed by cyrus-and** 2017-06-12 16:15 UTC
