### ISSUE TITLE
Have not figured how to catch "Inspector.detached"

### ISSUE THREAD

**Issue by JLS01** [cyrus-and/chrome-remote-interface#39] opened 2016-07-31 13:34 UTC
Hello "cyrus-and",

I am trying to catch the event when an existing remote chrome debugger session is terminated because the user opened in the tab the chrome developer tools. 

chrome.Inspector.enable();
chrome.Page.enable();
chrome.once('ready', function() {
   chrome.on('event', function (message) {
      console.log("chrome event:"+JSON.stringify(message));
   });
   chrome.Inspector.detached(function(response){
      console.log('Inspector for tab detached');
   });
});

This code will capture events like "Page.loadEventFired" without any issue but it will never capture "Inspector.detached".

I am using "chrome-remote-interface": "^0.12.3", thank you for your help.
#JLS01

For reference:
Upon disconnnection, the outgoing client will receive a detached event. For example: {"method":"Inspector.detached","params":{"reason":"replaced_with_devtools"}}
From: https://developer.chrome.com/devtools/docs/debugger-protocol

**Comment by cyrus-and** [comment] 2016-07-31 14:29
That happens because the WebSocket is closed by Chrome before any `Inspector.detached` is sent through it. I'm not sure if that's the intended behavior or a bug. In any case it does not seem compliant with the reference:

> Upon disconnnection, the outgoing client will receive a detached event.

A trivial solution might be emitting a `detach` event upon the `close` event of the WebSocket, so at least one can intercept the disconnection event. Let me better look into it...

**Comment by JLS01** [comment] 2016-07-31 14:41
Thank you very much for looking into this!

**Comment by cyrus-and** [comment] 2016-07-31 15:04
So it seems a bug with the [`ws`][1] library which interprets the disconnection as an abnormal close event (code [1006][2]) and fails to deliver the last message.This didn't happen with earlier versions, so as a quick fix you can force chrome-remote-interface to use [`ws`][1] version "0.4.32" (which I tried and works).

In the meanwhile if I'll be able to reproduce this in a minimal example I'll file an issue to [`ws`][1].

[1]: https://github.com/websockets/ws
[2]: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

**Comment by JLS01** [comment] 2016-07-31 15:15
Outstanding turn-around time for this workaround "cyrus-and" ! I can confirm that forcing "ws": "^0.4.32" in package.json of  chrome-remote-interface is fixing this issue for now. Thanks again.

**Comment by JLS01** [comment] 2016-08-06 14:04
I am seeing in the issue "ws- code 1006" comments that you are digging deeper yourself into this ws bug. I appreciate your efforts as using "ws": "0.4.32" is clearly only a workaround ("ws": "0.4.32" is causing itself as side effect unfortunately other instabilities using chrome-remote-interface) !

**Comment by cyrus-and** [comment] 2016-08-06 14:18
Actually there's a better workaround which works even with the latest version of ws. Replace [this line][1] with:

```js
    self.ws = new WebSocket(url, {'perMessageDeflate': false});
```

This disables the compression extension, which appears to be the cause of the issue. I will push this workaround if they'll take too long to fix the issue. After all having the compression enabled is a good thing.

[1]: https://github.com/cyrus-and/chrome-remote-interface/blob/1997b505afca4adbd5c34d42b2c284de8699c445/lib/chrome.js#L213

**Comment by JLS01** [comment] 2016-08-06 21:56
This solves indeed the problem of the event Inspector.detached and works with "ws": "^1.1.1". Thank you cyrus-and!

**Closed** 2016-08-12 16:13 UTC
