### ISSUE TITLE
chrome-remote-interface being fingerprinted

### ISSUE THREAD

**Issue by lobstrio** [cyrus-and/chrome-remote-interface#434] opened 2020-11-20 21:14 UTC
| Component | Version
|-|-
| Operating system	  	 	| ubuntu
| Node.js					| v10.22.0
| Chrome/Chromium/...		| Chrome
| chrome-remote-interface	| last version

Is Chrome running in a container? No

It seems to me that the debugging prototol is being detected by cloudflare last version :+1: 

This can be reproduced very consistently by visiting such website below

https://www.pharmacielafayette.com/bailleul

Would you have any advise on where to look ? 

Thanks in advance

**Comment by cyrus-and** [comment] 2020-11-21 11:31
I personally get the "Checking your browser before accessing pharmacielafayette.com." the first time even with my regular Chrome. I guess there are a number of variables, but after that, apparently the cookies and user agent must match:

```console
$ curl 'https://www.pharmacielafayette.com/enseigne' -s \
    -A 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36' \
    -b 'cookie=__cfduid=d8e27c6111f1d9deb34600c4bcd0412d91605957407' \
    -b 'cf_clearance=69033bcc40b03250a0081582aaebeb0102329635-1605957440-0-150' | grep '<title>'
<title>Pharmacie Lafayette  en Ligne | Parapharmacie | Prix Discount</title>
```

If I change something in the above I get `<title>Just a moment...</title>`.

Do you get the Cloudflare page if you try to load that website in an incognito session?

**Comment by lobstrio** [comment] 2020-11-21 12:09
@cyrus-and 

Thanks for your answer

1) With regular chrome (fresh session, without cookies) $ google-chrome-stable

We get `"Checking your browser before accessing pharmacielafayette.com."` then the browser will solve the challenge and access the website


2) With regular chrome (fresh session, without cookies) -> $ google-chrome-stable --remote-debugging-port=9222

We get `"Checking your browser before accessing pharmacielafayette.com."` but the browser never solves the challenge and we cannot access the website.


If we solve the challenge with regular chrome, and visit the website with the same session, then we wont get the challenge with 
`--remote-debugging-port=9222` enabled.

I hope I'm clear enough :pray

**Comment by cyrus-and** [comment] 2020-11-21 18:31
I cannot reproduce this, if I start (fresh, no cookies) Chrome with:

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222
```

The first time I get the Cloudflare page, then I wait and I access the website, the second time I go straight to the web page.

**Comment by cyrus-and** [comment] 2020-12-18 13:01
Closing for now, feel free to add any further details.

**Closed by cyrus-and** 2020-12-18 13:01 UTC
