### ISSUE TITLE
Page won't load and the code runs forever

### ISSUE THREAD

**Issue by Valeriu92** [cyrus-and/chrome-remote-interface#320] opened 2018-01-10 12:26 UTC
Hi, when I try to navigate to this page (with the headless option enabled) https://www.gsksaglik.com/internal-redirects.html the `page.loadEventFired` event is not fired and the browser won't close which makes the code to run forever...

This is my code:

```js
const CDP = require('chrome-remote-interface');
CDP((client) => {
    // extract domains
    const {Network, Page, Runtime} = client;
    // setup handlers
    Network.requestWillBeSent((params) => {
        console.log(params);
    });
    Page.loadEventFired(() => {
        client.close();
    });
    Network.loadingFailed(async(params) => {
        console.log(params);
    });

    // enable events then start!
    Promise.all([
        Network.enable(),
        Page.enable(),
        Runtime.enable()
    ]).then(() => {
        Network.clearBrowserCache();
        return Page.navigate({url: 'https://www.gsksaglik.com/internal-redirects.html'});
    }).catch((err) => {
        console.log('here');
        console.error(err);
        client.close();
    });
}).on('error', (err) => {
    // cannot connect to the remote endpoint
    console.error(err);
});
```

Is there any way I can load this page?

**Comment by cyrus-and** [comment] 2018-01-10 17:37
That's because it redirects to a PDF file. Duplicate of #315. Unfortunately I think this is a Chrome limitation.

**Closed by cyrus-and** 2018-01-10 17:37 UTC
