### ISSUE TITLE
Version 0.24.2 breaks `Emulation.forceViewport`

### ISSUE THREAD

**Issue by saurabh2590** [cyrus-and/chrome-remote-interface#203] opened 2017-07-18 15:05 UTC
Hi,
Our `package json` semver syntax allows `^0.24.1`  and hence led to upgrade to version `0.24.2` of `chrome-remote-interface`.
However, update to new version breaks the old code for `Emulation.forceViewport` complaining `Emulation.forceViewport is not a function` and it's not defined in `protocol.json` file as well.

Does it mean that protocol would make backward incompatible changes?
would be great if you could guide to use if there are any alternative functions enabled to achieve the same?

**Comment by cyrus-and** [comment] 2017-07-18 15:23
`Emulation.forceViewport` has been apparently removed from the tot protocol but it's still implemented in Chrome (up to 61 at least), I don't know whether this is an error or if it will be actually removed in the next versions of Chrome. In any case it was marked as `experimental`.

To use it anyway you can, as usual, invoke the *raw* version:

```js
client.send('Emulation.forceViewport', ...);
```

or fetch the protocol descriptor from Chrome:

```js
CDP({remote: true})...
```

**Comment by joelgriffith** [comment] 2017-07-18 17:25
Is there a channel of some kind (aside from the mailing list) where consumers can get better visibility into upcoming breaking-changes? I see that the protocol's docsite now annotates methods that are deprecated, which is fantastic, but hard to keep in step with.

**Comment by cyrus-and** [comment] 2017-07-19 12:21
@joelgriffith not super user-friendly but probably the most authoritative source; you can check the Git log of the two files as @paulirish said. Here are for convenience the direct links to the logs:

- [browser_protocol.json][1]
- [js_protocol.json][2]

[1]: https://chromium.googlesource.com/chromium/src/+log/master/third_party/WebKit/Source/core/inspector/browser_protocol.json
[2]: https://chromium.googlesource.com/v8/v8/+log/master/src/inspector/js_protocol.json

**Closed by cyrus-and** 2017-07-19 12:21 UTC

**Comment by hbakhtiyor** [comment] 2017-07-24 09:13
@paulirish @cyrus-and have issue hanging on `Page.captureScreenshot`, after updating to latest version, removed `Emulation.forceViewport` and changed `Emulation.setVisibleSize` to `Emulation.setDeviceMetricsOverride`.

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 16.04.2 LTS
| Node.js					| v8.2.1
| Chrome/Chromium/...		| Google Chrome 61.0.3159.5 dev
| chrome-remote-interface	| 0.24.2

**Comment by cyrus-and** [comment] 2017-07-24 09:45
@hbakhtiyor what is the issue exactly, that `Page.captureScreenshot` does not return? Please file a new issue if it's not related to this one. Changes to the `protocol.json` does not change the semantics of commands.

**Comment by hbakhtiyor** [comment] 2017-07-24 14:13
@cyrus-and yeah, stucks on `Page.captureScreenshot`, maybe issue with chrome itself

**Comment by hbakhtiyor** [comment] 2017-07-24 17:58
after changing `deviceScaleFactor` to `1` works well,

was

```js
    // Set up viewport resolution, etc.
    const deviceMetrics = {
      width: 1200,
      height: 1200,
      deviceScaleFactor: 0,
      mobile: false,
      fitWindow: false,
    };

    await Emulation.setDeviceMetricsOverride(deviceMetrics);
```

now

```js
    // Set up viewport resolution, etc.
    const deviceMetrics = {
      width: 1200,
      height: 1200,
      deviceScaleFactor: 1,
      mobile: false,
      fitWindow: false,
    };

    await Emulation.setDeviceMetricsOverride(deviceMetrics);
```

@paulirish @cyrus-and, is it the right behavior? when setting `deviceScaleFactor` to `0` doesn't work

**Comment by cyrus-and** [comment] 2017-07-24 19:41
@hbakhtiyor yes I can reproduce this, works with 60, doesn't with 61, yet it's off topic here. Since it looks like a possible Chrome bug you should ping the Google Group or file an issue at crbug.com
