### ISSUE TITLE
Loading is freezing after some time

### ISSUE THREAD

**Issue by hgfdd** [cyrus-and/chrome-remote-interface#147] opened 2017-06-01 18:45 UTC
Hello! I'm doing something like that:

```js
CDP((client) => {
    // extract domains
    const {Network, Page} = client;
    // setup handlers
    Network.requestWillBeSent((params) => {
        console.log(params.request.url);
    });
    Page.loadEventFired(() => {
        client.close();
    });
    // enable events then start!
    Promise.all([
        Network.enable(),
        Page.enable()
    ]).then(() => {
        return Page.navigate({url: 'https://github.com'});
    }).catch((err) => {
        console.error(err);
        client.close();
    });
}).on('error', (err) => {
    // cannot connect to the remote endpoint
    console.error(err);
});
```

After loadEventFired i execute some javascript in the page and close client. I'm doing this a lot of time for different sites. It's working well, but after some time it stop working. It can't load anything. The restart of chrome helps to solve this. 

What am i doing wrong? Hope on your response

**Comment by cyrus-and** [comment] 2017-06-01 19:29
This is the main example, AFAIK there's nothing wrong with it. You should allow me to reproduce your problem, can you show me your code and how you repeat the script for different sites?

Also, does the browser actually loads the last page or the load indicator keep spinning?

**Comment by hgfdd** [comment] 2017-06-01 20:15
```
CDP = require('chrome-remote-interface');

const options = {
    host: arg_host, port : chrome_port
};

CDP(options, (client) => {
  // Extract used DevTools domains.

  setTimeout(function()
  {
      console.log('Can\'t load the page...');
      client.close();
      process.exit(1);
  }, page_timeout);

  console.log('Extract used DevTools domains');
  const {Page, Network, Runtime, DOM, Security} = client;

  // Enable events on domains we are interested in.
  Promise.all([
    Page.enable(),
    Runtime.enable(),
    DOM.enable(),
    Security.enable()
  ]).then(() => {
    Security.certificateError(({eventId}) => {
        Security.handleCertificateError({
            eventId,
            action: 'continue'
        });
    });
   
    return Page.navigate({url: downloaded_url}).then((res) => { }); 
  }).catch((err) => {
        console.error(err);
        client.close();
	process.exit(1);
  });
  
  Page.domContentEventFired(() => {
       console.log('Page loaded...');
	
       var script = fs.readFileSync(readability_js, 'utf8');          
	
       var saveOutTitlePromise = saveOutTitle(Runtime);

       Promise.all([saveOutTitlePromise]).then(values =>
       {
           Runtime.evaluate({expression: script}).then((result) => {
       	        Runtime.evaluate({expression: 'document.documentElement.innerHTML = clearly()'}).then((result) => {
                        Runtime.evaluate({expression: 'document.documentElement.innerHTML'}).then((result) => {
				var plainTextPromise = getPlainText(Runtime);

                                //console.log(result);
                                var fs = require('fs');
				fs.writeFileSync(out, result.result.value, { mode: '666' });

                                console.log("The file was saved!");
				
				Promise.all([plainTextPromise]).then(()=>
				{
                                        client.close();
					console.log('Client closed!');
					process.exit(0);
				});
  			});  
		  });
            });
       });
   });
}).on('error', (err) => {
  console.error('Cannot connect to browser:', err)});
}
```
This is the main part of my code. I execute this script from another program for different urls. And after about ~2-3k  urls it stop loading any of them. As i said before, only restarting of chrome helps.

I don't fully understand your question, by the last pages are really loading in normal chrome.

**Comment by cyrus-and** [comment] 2017-06-03 09:39
> I execute this script from another program for different urls.

One execution after the other or somewhat in parallel?

> I don't fully understand your question, by the last pages are really loading in normal chrome.

Suppose that you're feeding http://example.com and then this issue happens, if you take a look at the Chrome window do you find http://example.com fully loaded or that it's still loading/incomplete.

> The restart of chrome helps to solve this.

I cannot immagine a way to break Chrome so that a restart is required using the CDP. When this happens, is there any Node.js instances still running? If this is the case, try to kill all those instances then restart loading URLs, if this is enough to solve this issue then maybe the last script execution fails to complete taking the ownership over the current tab thus preventing the successive instance to start.

But I'm not too sure as the `page_timeout` should trigger after some time...

**Comment by ErlendSB** [comment] 2017-06-07 07:27
I'm experiencing them same (but for certain requests).  
Requesting a simple page with a "heavy" image (6000x4500 pixels), results in Network.dataReceived stalling (for the image request).  
In this case, Page.loadEventFired never triggers, and a restart is needed.

**Comment by cyrus-and** [comment] 2017-06-07 10:27
@ErlendSB can you provide a reproducible example? Also, what version of Chrome?

**Comment by ErlendSB** [comment] 2017-06-07 12:08
```
const CDP = require('chrome-remote-interface');
const spawn = require('child_process').spawn;
const sleep = require('sleep-promise');


spawn('google-chrome', ['--headless', '--remote-debugging-port=9222', '--disable-gpu', '--no-sandbox', '--hide-scrollbars']);

async function example() {
	try {
                // wait for chrome to start
		await sleep(2000); 
		// connect to endpoint
		var client = await CDP();
		// extract domains
		const { Network, Page } = client;
		// setup handlers
		Network.requestWillBeSent((params) => {
			console.log(params.request.url);
		});
		Network.dataReceived((params) => {
			console.log('Network.dataReceived', params);
		});
		Page.loadEventFired((params) => {
			console.log('Page.loadEventFired', params);
		});
		// enable events then start!
		await Promise.all([Network.enable(), Page.enable()]);
		await Page.navigate({ url: 'https://static.pexels.com/photos/197935/pexels-photo-197935.jpeg' });
		await Page.loadEventFired();
	} catch (err) {
		console.error(err);
	} finally {
		if (client) {
			await client.close();
		}
	}
}

example();
```
I'm running it in a debian docker container, with google-chrome (59.0.3071.86-1)

**Comment by ErlendSB** [comment] 2017-06-07 12:42
Same issue with latest unstable (for debian): 60.0.3112.20-1

**Comment by cyrus-and** [comment] 2017-06-07 13:19
@ErlendSB yes, I can reproduce this. Funny thing is also that when it does not happen (i.e., when the Node.js process terminates) the code after `await Page.loadEventFired();` is not executed, this may happen if the Chrome process is killed before the `example()` promise is resolved thus allowing the Node.js process to terminate.

And actually the Chrome process is killed by `SIGBUS` in my case.

I mean, a successful run of the above script should print all the events and hang until the Chrome process is alive, so in either case there's something fishy going on here. Moreover if you fetch the list of targets while the above script hangs you get `[]`, you should get a JSON object with `id`, `type` and so on.

Later on today I will try with a proper Debian box (no Docker), but in any case I suspect that this is a Chrome bug that you should report [here][1].

[1]: https://bugs.chromium.org/p/chromium/issues/list

**Comment by cyrus-and** [comment] 2017-06-07 19:50
> Later on today I will try with a proper Debian box (no Docker)

And I cannot reproduce it, so it seems this is a Docker-related issue. Also, probably obvious but both Docker (Debian) on Debian and on macOS behave the same, i.e, `SIGBUS`, etc.

> but in any case I suspect that this is a Chrome bug that you should report here.

Even more positive about it.

**Comment by ErlendSB** [comment] 2017-06-08 07:32
Ok, good. I submitted an issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=730995

**Comment by cungminh2710** [comment] 2017-06-08 07:42
SIGBUS on Docker can be related to [shared memory issue](https://bugs.chromium.org/p/chromium/issues/detail?id=522853)

For comparison, on various container environments, /dev/shm can be much smaller by default.
- Heroku: 5MB
- Docker: 64MB
- Vagrant ubuntu/trusty64: 256MB

To fix /dev/shm issue, simply configure `--shm_size` to be 256 or more in Docker config. Or if you use docker-compose, use `shm_size: 256MB` in your service config

**Comment by ErlendSB** [comment] 2017-06-08 07:52
Excellent! That did it.

**Comment by cyrus-and** [comment] 2017-06-08 10:19
@cungminh2710 awesome, thanks!

@ErlendSB so I can close this assuming that the problem initially reported by @hgfdd is similar to this one (feel free to add comments if that's not the case).

**Closed by cyrus-and** 2017-06-08 10:19 UTC
Labels: external issue
