### ISSUE TITLE
Chrome not respecting emulateNetworkConditions

### ISSUE THREAD

**Issue by davidanetflix** [cyrus-and/chrome-remote-interface#79] opened 2017-02-10 20:45 UTC
I'm trying to use chrome-remote-interface to set the downloadThroughput and uploadThroughput of Chrome Canary.  I modified the sample to the following, but it doesn't seem like my download/upload is getting throttled.  If I directly set the network emulation using Chrome Developer Tools, it works as expected.  Any suggestions?  I wasn't sure what unit downloadThroughput and uploadThroughput are measured in, so I did try a variety of values.

```js
const CDP = require('chrome-remote-interface');
const Promise = require('bluebird');

CDP((client) => {
    // extract domains
    const {Network, Page} = client;
    // setup handlers
    Network.requestWillBeSent((params) => {
        console.log(params.request.url);
    });
    Page.loadEventFired(() => {
        client.close();
    });
    // enable events then start!
    Promise.all([
        Network.enable(),
        Page.enable()
    ]).then(() => {
        console.log(Network.emulateNetworkConditions);
        return Network.emulateNetworkConditions({
            offline: false,
            latency: 500,
            downloadThroughput: 500,
            uploadThroughput: 500
        });
    }).then(result => {
        console.log(result); // prints '{}'
        return Page.navigate({url: 'https://www.fast.com/'});
    }).delay(60000).catch((err) => {
        console.error(`ERROR: ${err.message}`);
        client.close();
    });
}).on('error', (err) => {
    console.error('Cannot connect to remote endpoint:', err);
});
```

**Comment by cyrus-and** [comment] 2017-02-12 22:42
By [inspect the inspector][1] (see "Sniffing the protocol", the anchor is broken) the unit of measurement seems to be bytes per second, e.g., the profile "DSL (5ms, 2.0Mb/s, 1.0Mb/s)" triggers the following message:

```js
{
    "id": 26,
    "method": "Network.emulateNetworkConditions",
    "params": {
        "offline": false,
        "latency": 5,
        "downloadThroughput": 262144, // (262144 [Bps] * 8) / (2 ** 20) = 2 [Mbps]
        "uploadThroughput": 131072,
        "connectionType": "other"
    }
}
```

So in your case you're trying to set ~4 KBps for both up and down throughput.

Now a problem with your code is that the connection is closed upon `Page.loadEventFired` which happens as soon as the page finished loading (it has nothing to do with the test itself). It's as though the DevTools is closed, thus restoring the original conditions.

Said that you're right, `Network.emulateNetworkConditions` doesn't work as intended anyway, in particular, with your settings the page is **very** slow to load yet tests are not, and it solely depends on the throughput, the delay seems to have no effect. This is very strange since this is basically the only thing that DevTools does when it's asked to throttle the network resources. The only thing that works reliably is setting `offline: true`.

I'm using the following code as a test case (I also have changed the website so to measure ping and upload throughput too):

```js
const CDP = require('chrome-remote-interface');

CDP((client) => {
    const {Network, Page} = client;
    Promise.resolve().then(() => {
        return Network.enable();
    }).then(() => {
        return Network.emulateNetworkConditions({
            offline: false,
            latency: 250,
            downloadThroughput: 262144,
            uploadThroughput: 131072
        });
    }).then((result) => {
        console.log(result);
        Page.navigate({url: 'http://beta.speedtest.net/run'});
    }).catch((err) => {
        console.error(err);
    });
}).on('error', (err) => {
    console.error('Cannot connect to remote endpoint:', err);
});
```

There's also another strange thing about `Network.emulateNetworkConditions`: it simply does not return (no error, nothing) if you pass some wrong arguments.

Moreover, I'm able to reproduce this issue by using the WebSocket directly:

```
$ wscat -c ws://localhost:9222/devtools/page/c9e345b0-d833-4463-91c2-d921e4a5110a
connected (press CTRL+C to quit)
> {"id": 1, "method": "Network.enable"}
< {"id":1,"result":{}}
> {"id": 2, "method": "Network.emulateNetworkConditions", "params": {"offline": false, "latency": 250, "downloadThroughput": 262144, "uploadThroughput": 131072}}
< {"id":2,"result":{}}
> {"id": 3, "method": "Page.navigate", "params": {"url": "http://beta.speedtest.net/run"}}
[...]
```

I suggest to ask the guys of the [Google Group][2] about this, feel free to use this issue as a reference.

[1]: https://developer.chrome.com/devtools/docs/debugger-protocol
[2]: https://groups.google.com/forum/#!forum/chrome-debugging-protocol

**Comment by cyrus-and** [comment] 2017-02-13 13:14
> Now a problem with your code is that the connection is closed upon Page.loadEventFired which happens as soon as the page finished loading (it has nothing to do with the test itself). It's as though the DevTools is closed, thus restoring the original conditions.

OK so it seems that once that this has been fixed (i.e., using my code snippet) the emulation on the website https://www.fast.com/ works as intended, it shows ~2Mb/s.

Still it doesn't for http://beta.speedtest.net/run, even using DevTools!

IMO it depends on how the tests are executed: while fast.com uses AJAX requests, beta.speedtest.net uses WebSockets. Most likely Chrome cannot perform network throttling on WebSockets, this may or may not be a problem in your case.

**Comment by cyrus-and** [comment] 2017-02-13 13:25
> Most likely Chrome cannot perform network throttling on WebSockets, this may or may not be a problem in your case.

Yep, there's an open [Chromium issue][1] about that.

I think I can safely close this issue, please let me know if you can't make it work for regular HTTP pages.

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=423246

**Closed by cyrus-and** 2017-02-13 13:25 UTC

**Comment by davidanetflix** [comment] 2017-02-14 18:46
Thanks for your help!   It was the client.close(); that was causing my issue.  Really appreciate you taking the time.
